# Ballerina demo config file
consumerKey = "LZdVfsLV18caWtRHqmyrUmhu2"
consumerSecret = "vAexySHptAQJqyEVpJWnLGevABHuPYeJhfesWfoNw3IVzTbrrn"
accessToken = "968237366-CMceM4v4hIKgzdNgrKl8zBLT1vm5ffksHKcrJtDe"
accessTokenSecret = "J3tGR8u1vVg4ekgAPluU1y1OvZuOcvUzJq2jLzMrGI6rN"